services:
  api:
    build:
      context: dotnet
      dockerfile: Stockr.API/Dockerfile
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      CLUSTER__CONSULURI: "http://consul:8500"
    ports: 
      - 8080:8080
    networks:
      - stockr
    depends_on:      
      silo:
        condition: service_started
      consul:
        condition: service_healthy

  silo:
    build:
      context: dotnet
      dockerfile: Stockr.Silo/Dockerfile
    environment:
      CLUSTER__CONSULURI: "http://consul:8500"
    depends_on:
      consul:
        condition: service_healthy
    networks:
      - stockr

  simulator:
    build:
      context: dotnet
      dockerfile: Stockr.StockSimulator/Dockerfile
    environment:
      CLUSTER__CONSULURI: "http://consul:8500"
    depends_on:
      silo:
        condition: service_started
      consul:
        condition: service_healthy

    networks:
      - stockr

  web:
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - 4200:4200

  consul:
    image: consul:1.15.2
    networks:
      - stockr
    healthcheck:
      # return information about the status of the Consul cluster https://www.consul.io/api/status.html
      test: ["CMD", "curl", "-X", "GET", "localhost:8500/v1/status/leader"]
      interval: 1s
      timeout: 3s
      retries: 60

networks:
  stockr: